### ISSUE TITLE
I can't find any several virtual devices in 'SmartHome'->Devices

### ISSUE THREAD

**Issue by sevencheng798** [alexa/alexa-smarthome#1]
Hi AlexaTeam,
i have done build a Working Smart Home Skill in 15 Minutes all of these steps. but i can't find any  virtual devices - Go to Smart Home > Devices and you should see several virtual devices. and when i said "Alexa, turn on switch", the alexa respone me "Sorry, i didn't find switch" Did i miss anyting? what should i do?

**Comment by sevencheng798** [comment]
Any comments or Do your need more information? tks

**Comment by mikemaas-amazon** [comment]
Hi Sven, 

When you do Discovery, do you get a list of the devices defined in the sample lambda? Lock, Switch, Thermostat, Baby Camera, Living Room Thermostat, White Light, and Light?

Beyond that, could you look at your CloudWatch logs for the SampleLambdaFunction and see if any errors are reported?

**Comment by dairong** [comment]
@sevencheng798, as per @mikemaas-amazon's suggestion, please also take a look at this FAQ: https://github.com/alexa/alexa-smarthome/wiki/Build-a-Working-Smart-Home-Skill-in-15-Minutes#faq

**Comment by sevencheng798** [comment]
@mikemaas-amazon @dairong Thanks it's working. there's some confusion with your guidance(https://github.com/alexa/alexa-smarthome/wiki/Validation-Schemas), especially the rookie like me, in fact i only copy 'validation_schemas/alexa_smart_home_message_schema.json' to 'sample_lambda/python/'.

**Comment by Wade-BuildOtto** [comment]
The Validation at least for node is out of date, Discovery now seems to have a "directive" root and the name spaces has changed from DiscoverApplianceRequest to Discover.Request

some of the example code doesn't work as directive is only on Discovery and not on the device change requests.

**Comment by Griffinx** [comment]
I have the same problem...Nothing is discovered. Could you give an update as to how to resolve please.

**Comment by briankel** [comment]
For folks who are facing issues, can you please check your CloudWatch logs for the Lambda for any clues? Usually this can help you to pinpoint the problem.

**Comment by Griffinx** [comment]
The discovery process isnt reaching the lambda at all in my case .. no invocations reported on the lambda console

**Comment by Griffinx** [comment]
It seems that you have to place your lambda in US West or it wont work

**Comment by briankel** [comment]
You do need to ensure you deploy into a region that supports Alexa, but it doesn't have to be US West (you'll know if a region is supported if you see "Alexa" in the list of available Triggers for your Lambda).

**Comment by dairong** [comment]
Assume the problem has been resolve by using the correct Lambda region and adding the right trigger. Resolving, please re-open if problem persists, thanks!
