### ISSUE TITLE
ModeController

### ISSUE THREAD

**Issue by madgeni** [alexa/alexa-smarthome#104]
Hi - is this fully GA now? 
If I include it (the JSON checks out) - nothing comes back. 
Is it just me?

**Comment by madgeni** [comment]
response for ModeController:
`{
                            "type": "AlexaInterface",
                            "interface": "Alexa.ModeController",
                            "version": "3",
                            "instance": "TV control.Level",
                            "capabilityResources": {
                                "friendlyNames": [
                                    {
                                        "value": {
                                            "text": "Level",
                                            "locale": "en-US"
                                        }
                                    },
                                    {
                                        "value": {
                                            "text": "modus",
                                            "locale": "de"
                                        }
                                    }
                                ]
                            },
                            "properties": {
                                "supported": [
                                    {
                                        "name": "mode"
                                    }
                                ],
                                "retrievable": true,
                                "proactivelyReported": true
                            },
                            "configuration": {
                                "ordered": false,
                                "supportedModes": [
                                    {
                                        "value": "TV control.Off",
                                        "modeResources": {
                                            "friendlyNames": [
                                                {
                                                    "value": {
                                                        "text": "Off",
                                                        "locale": "en-US"
                                                    }
                                                }
                                            ]
                                        }
                                    },
                                    {
                                        "value": "TV control.tv",
                                        "modeResources": {
                                            "friendlyNames": [
                                                {
                                                    "value": {
                                                        "text": "tv",
                                                        "locale": "en-US"
                                                    }
                                                }
                                            ]
                                        }
                                    },
                                    {
                                        "value": "TV control.Game",
                                        "modeResources": {
                                            "friendlyNames": [
                                                {
                                                    "value": {
                                                        "text": "Game",
                                                        "locale": "en-US"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                ]
                            }
                        }`

**Comment by typasch** [comment]
This is in GA for en-US customers.  I think that "modus" in de might be causing issues.

**Comment by madgeni** [comment]
Fair point - removed the DE mode, still no dice :(

**Comment by typasch** [comment]
@madgeni  You're missing "@type": "text", for each of our value: blocks.  

Example: https://developer.amazon.com/docs/device-apis/alexa-modecontroller.html

**Comment by madgeni** [comment]
@typasch had it right - the issue was the lack of the @type - thank you!

**Comment by msjonathan** [comment]
@madgeni Where you able to make use of the ModeController with a skill deployed in Europe? Or is it still only GA in the US?

**Comment by madgeni** [comment]
Mine is still only configured for US - i'm guessing it's another capability that isn't available outside the US

**Comment by msjonathan** [comment]
@madgeni thanks for the fast response 👍  - I did a test on my Europe hosted skill and returned the raw json sample of the documentation and it did not discover in the Alexa app so your guess will be correct. 

To be honest I am really missing an overview by Amazon itself on what capabilities they support and in which region they support it, that would make developing much easier.

**Comment by karstenkegler** [comment]
You know this?
https://developer.amazon.com/de/docs/device-apis/list-of-interfaces.html
