### ISSUE TITLE
alexa_smart_home_message_schema.json not upto date

### ISSUE THREAD

**Issue by kakopappa** [alexa/alexa-smarthome#136]
Hi guys, 

Seems GARAGE_DOOR missing in alexa_smart_home_message_schema.json

![image](https://user-images.githubusercontent.com/7474406/71454841-1d30cf00-27c5-11ea-9c17-f53f9801f9a7.png)

**Comment by jsetton** [comment]
I included the latest display categories in PR #112

**Comment by helviojr** [comment]
So this issue should be closed?
