### ISSUE TITLE
[Step 1.1.8] Unable to Create Stack

### ISSUE THREAD

**Issue by lukenewman** [alexa/alexa-smarthome#16]
I'm on step 1.1.8 and getting a `ROLLBACK` due to the following error:

![screen shot 2017-11-29 at 1 45 47 pm](https://user-images.githubusercontent.com/5315645/33392985-a4e0a196-d50b-11e7-9514-aa7097a6de66.png)

This is my second time going through the tutorial. The first time I had no issues with this step, so I'm not sure what could be causing it now.

Any help you could provide is much appreciated -- thanks!

**Comment by mikemaas-amazon** [comment]
It was a temporary condition, should be resolved now. Please try again.
