### ISSUE TITLE
Validation schema fails to parse in Node.js

### ISSUE THREAD

**Issue by camdendobrien** [alexa/alexa-smarthome#174]
I'm trying to create some integration tests for a smart home skill back-end using the validation schema in this repository, but when I try to parse the file (using `JSON.parse`) I get an error:
```javascript
> JSON.parse(fs.readFileSync('alexa_smart_home_message_schema.json', 'utf-8'))
Uncaught SyntaxError: Unexpected token } in JSON at position 262146
```
It's odd because looking at that part of the file it looks absolutely fine:
```json
...
"proactivelyReported": {
    "oneOf": [
        {
            "type": "boolean"
        },
        {
            "type": "string",
            "enum": [
                "true",
                "false",
                "True",
                "False",
                "TRUE",
                "FALSE"
            ],
        }, // error is on this '}'
        {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1
            ]
        }
    ]
},
...
```

**Comment by callumdavidobrien** [comment]
There is actually a syntax error in the schema, will open a PR to fix it shortly.

**Comment by Relequestual** [comment]
While dangling commas are fine in JavaScript, they are not allowed in JSON. This seems to be the issue.

**Comment by Relequestual** [comment]
Looks like the schema is machine-generated! So you may have to dig into how, and fix the issue in code, rather than just PR the schema file.

**Comment by callumdavidobrien** [comment]
> Looks like the schema is machine-generated! So you may have to dig into how, and fix the issue in code, rather than just PR the schema file.

Oh ok, that's a pain :joy:

**Comment by callumdavidobrien** [comment]
Can't find any information on how the schema is generated, hopefully will hear from the maintainers at some point ¯\_(ツ)_/¯

**Comment by Relequestual** [comment]
I don't think the code required to do this is in this repo, nor the source.
The repo readme just says "resources".

Also suggest, add tests to check that schemas provided are...

1. Valid JSON
2. Valid JSON Schema

**Comment by Sowmyanalluri** [comment]
Closing this issue as there is a closed pull request  https://github.com/alexa/alexa-smarthome/pull/175
