### ISSUE TITLE
Python 3.6 runtime with AWS Lambda does not work with AWS IoT Data.

### ISSUE THREAD

**Issue by rlbartle** [alexa/alexa-smarthome#21]
As discussed on [AWS Forums](https://forums.aws.amazon.com/thread.jspa?messageID=810982#810982), the python 3.6 runtime used here, uses OpenSSL 1.0.0-fips, which doesn't support TLS 1.2 which is necessary in order to connect with AWS IoT.  

This affects the usefulness of the sample because after successfully running the lambda sample, developers expect to be able to extend it to support loading endpoints dynamically according to their own design.  ie.  With DynamoDB and IoT, users and things are associated, and the lambda function will determine what things the Alexa authorized user has access to and display them.  That is the next logical implementation step, but this issue blocks that.

**Comment by mikemaas-amazon** [comment]
This seems like a AWS Lambda issue but I will ask: How exactly are you connecting to AWS IoT?

**Comment by rlbartle** [comment]
Using boto3.  


```
import boto3

...

client = boto3.client("iot-data", "us-east-2")
client.get_thing_shadow()

```

In the meantime, I am able to have it running by using the 2.7 runtime and including the functools32 package which is needed by jsonschema.

**Comment by mikemaas-amazon** [comment]
I saw this as a warning in the CloudWatch logs but it did not prevent me from using Python 3.6 in my Lambda to access iot-data via Boto3. Closing.
