### ISSUE TITLE
Error on enabling skill

### ISSUE THREAD

**Issue by keithcaskey** [alexa/alexa-smarthome#22]
I followed this tutorial only to be faced with this error at the end of it. What am I missing here?

![capture](https://user-images.githubusercontent.com/4714319/33814350-ac2f5f2e-ddf7-11e7-8c8b-84e41c3e0a9d.PNG)

**Comment by briankel** [comment]
@keithcaskey did you remember to follow this step?

Provide Redirect URL's to LWA:
The Configuration page for your Skill lists several Redirect URL's. Open the LWA security profile you created earlier and visit the Web Settings dialog. Provide each of the Redirect URL values from your Skill in the Allowed Return URL's field.

**Comment by mikemaas-amazon** [comment]
Brian's suggestion is likely the correct path. The URIs you will need to put into your security profile will look like the following:

https://pitangui.amazon.com/api/skill/link/XXXXXXXXXXXXX
https://layla.amazon.com/api/skill/link/XXXXXXXXXXXXX
https://alexa.amazon.co.jp/api/skill/link/XXXXXXXXXXXXX
