### ISSUE TITLE
ColorController

### ISSUE THREAD

**Issue by pevecyan** [alexa/alexa-smarthome#25]
Hi, could someone please share discovery sample for ColorController device, I cannot find it in the documentation.

Thanks!

**Comment by mikemaas-amazon** [comment]
https://developer.amazon.com/docs/device-apis/alexa-colorcontroller.html#reportable-properties outlines the reportable properties. For ColorController that is only "color". Your discovery response will need to include an Alexa.Interface for Alexa.ColorController that defines "color" as a supported property. If you look at the capabilities JSON section of https://github.com/alexa/alexa-smarthome/blob/master/sample_messages/Discovery/Discovery.response.json you should be able to extrapolate.
