### ISSUE TITLE
Alexa Scene response - "something went wrong"

### ISSUE THREAD

**Issue by Wade-BuildOtto** [alexa/alexa-smarthome#3]
The scene activates no problem, I but the response I give back which matches the example, it doesn't like is the example out of date?

{
    "context": {
        "properties": [
            {
                "namespace": "Alexa.EndpointHealth",
                "name": "connectivity",
                "value": {
                    "value": "OK"
                },
                "timeOfSample": "2017-10-24T17:44:26.519Z",
                "uncertaintyInMilliseconds": 200
            }
        ]
    },
    "event": {
        "header": {
            "namespace": "Alexa.SceneController",
            "name": "ActivationStarted",
            "payloadVersion": "3",
            "messageId": "7f5179bd-3e3f-4a04-8455-018b71216fdc-R",
            "correlationToken": "XXX=="
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "XXXMtSSVwoZhJhy7_7G6p"
            },
            "endpointId": "MwjLhmGjmgoLWSe4a"
        }
    },
    "payload": {
        "cause": {
            "type": "VOICE_INTERACTION"
        },
        "timestamp": "2017-10-24T17:44:26.519Z"
    }
}

It matches the sample online

https://github.com/alexa/alexa-smarthome/blob/master/sample_messages/SceneController/SceneController.ActivationStarted.message.json

**Comment by dairong** [comment]
@Wade-BuildOtto, does this problem still persist?

**Comment by dansampson** [comment]
Yes. I am seeing the exact same thing.
