### ISSUE TITLE
Forget All button was removed.

### ISSUE THREAD

**Issue by jorgecis** [alexa/alexa-smarthome#4]
Now that the Forget All button was removed in the smart home list, what is the discovery response to delete/remove a device that doesn't exist anymore? Right now if the discovery response does not include the endpoint this one become offline but is still there, and the user can't remove it, not event disable the skill

**Comment by nathforge** [comment]
Just found [this comment](https://community.smartthings.com/t/amazon-alexa-sent-refresh-command-to/102921/11):

> Spoke with amazon support - the ability to delete devices in the alexa app is not coming back per the rep.
>
> You can however login to the alexa web interface and the delete option is still present and works properly.

**Comment by jorgecis** [comment]
Woow really, for me this is a critical issue, is affecting all smart home skill, if the skill "Nest, smartthings, etc"   added a device to the list, is impossible to delete/remove it!!!, and is worst, because if you enable the skill again you will end with 2 devices with the same name!!.

**Comment by dairong** [comment]
Thank you both for the feedback. First, the "forget all" concept, though removed now, will most likely return in a different format in the Alexa App, so please watch out for that. With respect to SmartThings, we did have some issues after the v3 skill launch that required some time to debug. Those should be resolved now. Please re-open if problems persist, thanks!
