### ISSUE TITLE
How to control the LED of Raspberry Pi with aws Lambda

### ISSUE THREAD

**Issue by sungjinp11** [alexa/alexa-smarthome#5]
I installed Alexa in the raspberry pi.
I want to control the LED on the Raspberry pi using the AWS Lambda. It seems that YouTube only uses flask-ask.
I want to control the LED on the raspberry pi with the Lambda Function.
I want you to tell me how.

**Comment by sungjinp11** [comment]
I want to use Python language.

**Comment by dairong** [comment]
@sungjinp11, this question is beyond the scope of this repo. This forum question and answer may help: https://forums.developer.amazon.com/questions/93604/how-to-control-the-led-sensors-of-raspberry-pi-bas.html, thanks!
