### ISSUE TITLE
Validation schema does not include PlaybackController

### ISSUE THREAD

**Issue by jordantomax** [alexa/alexa-smarthome#62]
Spent the better part of an afternoon banging my head against this one until I realized that `PlaybackController` is simply not included in the Validation Schema!!

Is this intentional? If I was to write the code to validate it, would you look at a PR?

**Comment by jordantomax** [comment]
Hi there, just checking in about this issue. Are you uninterested in updating the validation to handle `PlaybackController`? Thanks.

**Comment by sumitdang** [comment]
PlaybackController is now added to validation schemas. Closing this ticket now.
