### ISSUE TITLE
Necessary to support v2?

### ISSUE THREAD

**Issue by philfreo** [alexa/alexa-smarthome#7]
Loved the simple 15 minute wiki format.

I was surprised to see a bunch of code in https://github.com/alexa/alexa-smarthome/blob/master/sample_lambda/python/lambda.py trying to support both v2 and v3. 

Correct me if I'm wrong, but this is targeted at new skill creation where you would only need to support v3, right? If so, I would suggest significantly simplifying the code to support only v3. Or am I missing something?

**Comment by briankel** [comment]
Thanks Phil, I'm glad you enjoyed it. Yes at some point we will be deprecating the v3 information from the samples. For the time being some Smart Home partners are still in the process of migrating to v3. You are correct that if you're building a new skill you can go purely v3. Thanks for checking!
