### ISSUE TITLE
Open/close actions

### ISSUE THREAD

**Issue by atlascoder** [alexa/alexa-smarthome#74]
Hello guys!

I am trying to create a skill for Smart Home devices of window shades type. I'd like to get Alexa understand "Open shades in kitchen", but no luck in Alexa interfaces to get working - i get "shades kitchen doesn't support that."

From other side, I tried to create a custom skill and Alexa does recognize Open/Close commands as one from HomeAutomation domain:

    "payload": {
        "caption": "shades kitchen doesn't support that.",
        "url": "https://kopytko.amazon.com/2/2304d013-5e07-11e8-914c-b9759d765ccc-418334/5/1527110937999/8f265458ceb8a90b5f50fa0f4a50b056dd37d951f575dc43639699e8e21e94f3/resource.mp3",
        "format": "AUDIO_MPEG",
        "token": "amzn1.as-ct.v1.HomeAutomation#ACRI#DeviceTTSRendererV4_524bf82e-5b5f-45ef-88a4-e5855c67b7ee",
        "ssml": "<speak><prosody volume=\"x-loud\">shades kitchen doesn't support that.</prosody><metadata><promptMetadata><promptId>ExecuteAction.UnsupportedCapability</promptId><namespace>HomeAutomation</namespace><locale>en_US</locale><overrideId>default</overrideId><variant>7c9d0ff6-0e21-454a-bb7f-f252a9253f36</variant><condition/><weight>1</weight><stageVersion>Adm-20170525_233945-165</stageVersion></promptMetadata></metadata></speak>"
    }

I saw several posts on Amazon forum where people ask to implement such interface - do you have any plan about that? If yes - then when?

Thanks a lot!!

**Comment by briankel** [comment]
Thanks for your interest! It's not something we support today but it's definitely on our backlog. We don't have a timeline to share right now.
