### ISSUE TITLE
Can't find 'Alexa Smart Home' in triggers of a new Lambda function

### ISSUE THREAD

**Issue by greenskii** [alexa/alexa-smarthome#78]
I was following the Wiki to create a smart home skill, 
https://github.com/alexa/alexa-smarthome/wiki/Build-a-Working-Smart-Home-Skill-in-15-Minutes

but at step "Step 3: Click Triggers -> Add Trigger and select Alexa Smart Home"
I can't find any Alexa Smart Home in the trigger list.

![bug alexa](https://user-images.githubusercontent.com/22318639/41472254-2956edae-70b6-11e8-944c-498678b686f7.png)

Please could you check if this is a bug?

**Comment by greenskii** [comment]
Found the answer. You have to select the correct DataCenter :
N.Virginia for English (US) or English (CA) skills
EU (Ireland) region for English (UK), English (IN), German or French (FR) skills
US West (Oregon) for Japanese and English (AU) skills.
The region is displayed in the upper right corner. Providing your Lambda function in the correct region prevents latency issues.

**Comment by Mikelinoss** [comment]
Hi, I had the same issue, but I couldn't solve it as you reported (changing the region). Can you explain a little more? Or, does anyone had the same problem with an alternate solution? Thank you.
