### ISSUE TITLE
How to handle non LWA authentication

### ISSUE THREAD

**Issue by albinantony2904** [alexa/alexa-smarthome#8]
I am planning to direct the user to a login page that I provide in companion app when the user tries to enable a smart home skill.So how can I handle such kind of authentication.? Is there any tutorial available that does not involve LWA authentication.?

**Comment by modescode** [comment]
Here's a blog, as a guide for LwA implementation - https://developer.amazon.com/blogs/post/Tx3CX1ETRZZ2NPC/Alexa-Account-Linking-5-Steps-to-Seamlessly-Link-Your-Alexa-Skill-with-Login-wit

**Comment by albinantony2904** [comment]
@modescode I don't want to use LWA

**Comment by briankel** [comment]
@albinantony2904 setting up the OAuth provider is not something we can provide documentation for as this will vary greatly depending on the web platform you are using. However we do have some documentation which can help you with configuration based on what Alexa is expecting:

- https://developer.amazon.com/docs/smarthome/authenticate-an-alexa-user-account-linking.html
- https://developer.amazon.com/docs/smarthome/authenticate-a-customer-permissions.html

**Comment by dairong** [comment]
To add to @modescode and @briankel's comments, we expect smart home skill authorization to be based on the [OAuth 2 spec](https://tools.ietf.org/html/rfc6749), so if you do not want to use LWA, then you can use any other OAuth 2 compliant provider. Resolving this issue, please re-open if needed, thanks!
