### ISSUE TITLE
We were unable to link Test at this time.

### ISSUE THREAD

**Issue by reejinbouk** [alexa/alexa-smarthome#83]
Hello,
I've make skill + backend server for smart home
But when I'm trying to link , I got this error after successful authorization on my server:
https://skills-store.amazon.com/external/link-result?success=false&languageCode=en_US&skillId=amzn1.ask.skill.7_______________&skillStage=development

**We were unable to link Test at this time.**

And my backend server log this (server written with Go, SSL certificate by Comodo):
**2018/08/12 01:52:15 server.go:2923: http: TLS handshake error from 72.21.217.157:5265: remote error: tls: unknown certificate**

I found whois for 72.21.217.157 - it's Amazon server, so I think that first step is ok, after authorization my server redirect to skills-store.amazon.com and Amazon server request something, but without SSL certificate.
How can I check this or fix?
Thank you

**Comment by reejinbouk** [comment]
Hello, I've found error with certificate and fix it
But now still get same error.
My server send JSON on request to token URI:
{
    "token_type": "bearer",
    "access_token": "e10972d4-4afa-4c2b-b2f3-59753e5c7cc6",
    "refresh_token": "febc7e9f-d458-48fb-8a24-5123d87f8ba1",
    "expires_in": 3600
}

I've check it with Postman. But still got We were unable to link Test at this time.

What can I check or fix else?

**Comment by mikemaas-amazon** [comment]
Both of those Tokens look to be incorrect as access tokens. They are typically much longer and not just a GUID. For example, a token returned from Login with Amazon (LWA) would look be prefixed with Atza| and followed by a very long bearer token string. See https://developer.amazon.com/docs/login-with-amazon/access-token.html for an example. (But even their example is truncated)

**Comment by iroboteer** [comment]
@reejinbouk  
Are you resolved this issue ?

**Comment by reejinbouk** [comment]
yes, thank you

**Comment by iroboteer** [comment]
@reejinbouk 
Thank you reply.
I also found the same problem, I want to know how to solve this problem, can you tell me your solution ？
Thank you very much.
