### ISSUE TITLE
Validation scheme is not working.

### ISSUE THREAD

**Issue by Sharvin26** [alexa/alexa-smarthome#91]
I am using the validation schema in the above code and I am getting a oneOf error when operating on the devices from the companion app. Even the devices couldn't be discovered and getting the error "can't find any devices" on the Alexa Companion App.
Is this validation schema made for V2 payload only??

**Comment by pinoyyid** [comment]
I found that, to get the example working, I needed to comment out line 222: `validate_message(request, response)`

**Comment by Sharvin26** [comment]
Currently, I am working on that basis only. Removing the validation won't be a proper way in the long run. I wanted to know what changes they have made in v3 validation (Not Sure about it though) or what's making the validation fail so to fix it.

**Comment by Sharvin26** [comment]
Well, there is not a bug in the validation. This is not a complete Schema if you add something in the code then add a validation for that purpose
